name: NPM Publish

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    name: NPM Publish
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ endsWith(github.ref_name, 'next') && 'next' || 'latest' }}


